apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-v1
  labels:
    app: product-v1
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: product-v1
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: product-v1
    spec:
      containers:
        - name: product-v1
          image: miguelarmasabt/product:v1.0.1
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8017
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: cm-product-v1
                  key: mysql-host
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-product-v1
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-product-v1
                  key: mysql-password
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cm-product-v1
                  key: database
      
