apiVersion: v1
kind: Service
metadata:
  name: product-v1
  labels:
    app: product-v1
spec:
  type: NodePort
  selector:
    app: product-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: product-v1
      port: 8017
      nodePort: 30017
