server:
  port: 8888

spring:
  application:
    name: config-server-v1

  profiles:
    active: native #file system
#    active: git

  #retrieve properties from git repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miguel-armas-abt/demo-microservices-bbq.git
          default-label: config-server
          basedir: ./src/main/resources/git-config
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true