apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-hub-v1
  labels:
    app: order-hub-v1
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: order-hub-v1
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: order-hub-v1
    spec:
      containers:
        - name: order-hub-v1
          image: miguelarmasabt/order-hub:v1.0.1
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8018
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe: #decide whether to restart the pod
            httpGet:
              path: /actuator/health/liveness
              port: 8018
            initialDelaySeconds: 30 #wait for the service to start and stabilize before the first check
            periodSeconds: 30 #frequency of liveness checks
            timeoutSeconds: 5 #If the service is not available after a timeout period, the failure counter is increase
            failureThreshold: 3 #failure threshold to cancel the pod execution and provide a new replica
          readinessProbe: #decide whether to send traffic to the pod
            httpGet:
              path: /actuator/health/readiness
              port: 8018
            initialDelaySeconds: 30 #wait for the service to start and stabilize before the first check
            periodSeconds: 30 #frequency of readiness checks
          env:
            - name: CONFIG_SERVER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: config-server-domain
            - name: MENU_V1_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: menu-v1-domain
            - name: MENU_V2_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: menu-v2-domain
            - name: TABLE_PLACEMENT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: table-placement-domain
            - name: INVOICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: invoice-domain
            - name: REDIS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: redis-domain
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-order-hub-v1
                  key: java-opts
      
