apiVersion: v1
kind: Service
metadata:
  name: order-hub-v1
  labels:
    app: order-hub-v1
spec:
  type: NodePort
  selector:
    app: order-hub-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: order-hub-v1
      port: 8018
      nodePort: 30018
