apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1 #number of pods replicas
  
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: mysql-db
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 3306
          envFrom: #read envars from secret file
            - secretRef:
                name: secret-mysql-db
          volumeMounts:
            #this is the path in the container on which the mounting will take place.
            - mountPath: /var/lib/mysql-db/data
              name: mysql-db-volume-data
            - mountPath: /docker-entrypoint-initdb.d/initdb.sql
              subPath: initdb.sql
              name: mysql-db-volume-script
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: mysql-db-volume-data
          persistentVolumeClaim:
            claimName: pvc-mysql-db
        - name: mysql-db-volume-script
          configMap:
            name: cm-mysql-db
