apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  type: NodePort
  selector:
    app: mysql-db
  clusterIP: 10.96.1.2

  ipFamilies:
    - IPv4
  ports:
    - name: mysql-db
      port: 3306
      nodePort: 30006
