application:
  http-client:
    menu-option-v2:
      base-url: ${BUSINESS_MENU_OPTION_BASE_PATH:http://localhost:8016/bbq/business/v2/}
    dining-room-order-v1:
      base-url: ${BUSINESS_DINING_ROOM_ORDER_BASE_PATH:http://localhost:8010/bbq/business/v1/}

kafka-broker:
  topic:
    invoice: invoice-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bbq

business:
  invoice:
    igv: 0.18
