spring:

  sql:
    init:
      mode: always #read data.sql or schema sql, default value is embedded, only for integrated db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    defer-datasource-initialization: true #read data.sql file after schema generation by hibernate

  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://127.0.0.1:5432/db_dining_room_orders?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME:bbq_user}
    password: ${POSTGRESQL_PASSWORD:qwerty}

application:
  http-client:
    menu-option:
      v1:
        base-url: ${BUSINESS_MENU_OPTION_V1_BASE_PATH:http://localhost:8080/bbq/business/v1/}
      v2:
        base-url: ${BUSINESS_MENU_OPTION_V2_BASE_PATH:http://localhost:8810/bbq/business/v2/}
      selector-class: com.demo.bbq.business.diningroomorder.infrastructure.repository.restclient.menuoptionv2.retrofit.MenuOptionV2ApiConnectorRetrofitImpl
      selector-class-fallback: com.demo.bbq.business.diningroomorder.infrastructure.repository.restclient.menuoptionv1.retrofit.MenuOptionV1ApiConnectorRetrofitImpl

resilience4j:
  circuitbreaker:
    instances:
      menu-option:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
