spring:

  sql:
    init:
      mode: always #read data.sql or schema sql, default value is embedded, only for integrated db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
    defer-datasource-initialization: true #read data.sql file after schema generation by hibernate

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/db_menu_options?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:bbq_user}
    password: ${MYSQL_PASSWORD:qwerty}

application:
  http-client:
    product:
      base-url: ${PRODUCT_V1_BASE_URL:http://localhost:8017/bbq/business/product/v1/}
