server:
  port: 8011

spring:
  application:
    name: auth-adapter-v1

keycloak:
  server: http://${KEYCLOACK_DOMAIN:localhost:8091}/auth/realms
  base-url: ${keycloak.server}/bbq-management/protocol/openid-connect/
  authorization-uri: ${keycloak.base-url}auth
  jwk-set-uri: ${keycloak.base-url}certs
  certs-id: ${KEYCLOACK_KEY_RS256:HyN8eTuKg02Lx3iSaKjsZHKor2ouz2WQ_i50fhMy0bk}
  client-id: front-bbq-app
  client-secret: qwerty
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token
