server:
  port: 8011

spring:
  application:
    name: auth-adapter-v1

keycloak:
  server: http://${KEYCLOACK_DOMAIN:localhost:8091}/auth/realms
  base-url: ${keycloak.server}/bbq-management/protocol/openid-connect/
  authorization-uri: ${keycloak.base-url}auth
  jwk-set-uri: ${keycloak.base-url}certs
  certs-id: ${KEYCLOACK_KEY_RS256:_t8Avn1u-Dc9fk7Gw_-za6j1g5iL44C6X3N6Rayp59A}
  client-id: front-bbq-app
  client-secret: qwerty
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always