kind: Service
apiVersion: v1
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper-server
spec:
  type: NodePort
  selector:
    app: zookeeper-server
  ports:
    - name: zookeeper-server
      port: 2181
      nodePort: 30181
