apiVersion: v1
kind: Service
metadata:
  name: zookeeper-server
  labels:
    app: zookeeper-server
spec:
  type: NodePort
  selector:
    app: zookeeper-server
  
  ipFamilies:
    - IPv4
  ports:
    - name: zookeeper-server
      port: 2181
      nodePort: 30181
