apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-v2
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: menu-v2
  template:
    metadata:
      labels:
        app: menu-v2
    spec:
      containers:
        - name: menu-v2
          image: miguelarmasabt/menu:v2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8016
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
            - name: MYSQL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-menu-v2
                  key: mysql-domain
            - name: PRODUCT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-menu-v2
                  key: product-domain
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-menu-v2
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-menu-v2
                  key: mysql-password
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-menu-v2
                  key: java-opts
