kind: Service
apiVersion: v1
metadata:
  name: menu-v2
  labels:
    app: menu-v2
spec:
  type: NodePort
  selector:
    app: menu-v2
  ports:
    - name: menu-v2
      port: 8016
      nodePort: 30016
