apiVersion: v1
kind: Service
metadata:
  name: menu-v2
  labels:
    app: menu-v2
spec:
  type: NodePort
  selector:
    app: menu-v2
  
  ipFamilies:
    - IPv4
  ports:
    - name: menu-v2
      port: 8016
      nodePort: 30016
