apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-v1
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: config-server-v1
  template:
    metadata:
      labels:
        app: config-server-v1
    spec:
      containers:
        - name: config-server-v1
          image: miguelarmasabt/config-server:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cm-config-server-v1
                  key: eureka-server
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-config-server-v1
                  key: java-opts
