apiVersion: v1
kind: Service
metadata:
  name: config-server-v1
  labels:
    app: config-server-v1
spec:
  type: NodePort
  selector:
    app: config-server-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: config-server-v1
      port: 8888
      nodePort: 30088
