apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-v1
  labels:
    app: invoice-v1
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: invoice-v1
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: invoice-v1
    spec:
      containers:
        - name: invoice-v1
          image: miguelarmasabt/invoice:v1.0.1
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8014
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: CONFIG_SERVER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: config-server-domain
            - name: KAFKA_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: kafka-domain
            - name: POSTGRESQL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: postgresql-domain
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: postgresql-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: postgresql-password
            - name: PRODUCT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: product-domain
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-invoice-v1
                  key: java-opts
      
