apiVersion: v1
kind: Service
metadata:
  name: invoice-v1
  labels:
    app: invoice-v1
spec:
  type: NodePort
  selector:
    app: invoice-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: invoice-v1
      port: 8014
      nodePort: 30014
