kind: Service
apiVersion: v1
metadata:
  name: invoice-v1
  labels:
    app: invoice-v1
spec:
  type: NodePort
  selector:
    app: invoice-v1
  ports:
    - name: invoice-v1
      port: 8014
      nodePort: 30014
