server:
  port: 8011

spring:
  application:
    name: auth-adapter-v1

keycloak:
  server: ${KEYCLOACK_SERVER:http://localhost:8091}
  base-uri: ${keycloak.server}/auth/realms/bbq-management/protocol/openid-connect/
  authorization-uri: ${keycloak.base-uri}auth
  jwk-set-uri: ${keycloak.base-uri}certs
  certs-id: ${KEYCLOACK_KEY_RS256:mH6KTBOtG3B8_UcrOvA6zPn23SdGeqpp5YOp-MHR0Fo}
  client-id: front-bbq-app
  client-secret: qwerty
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging.level.root: INFO
