configuration:
  show-custom-messages: false

  rest-clients:
    menu-v1:
      request:
        endpoint: http://${MENU_V1_DOMAIN:localhost:8080}/bbq/business/menu/v1/
        headers:
          Accept: application/json
    menu-v2:
      request:
        endpoint: http://${MENU_V2_DOMAIN:localhost:8016}/bbq/business/menu/v2/
        headers:
          Accept: application/json
    table-placement-v1:
      request:
        endpoint: http://${TABLE_PLACEMENT_DOMAIN:localhost:8013}/bbq/business/table-placement/v1/
        headers:
          Accept: application/json
    invoice-v1:
      request:
        endpoint: http://${INVOICE_DOMAIN:localhost:8014}/bbq/business/invoice/v1/
        headers:
          Accept: application/json

  variables:
    menu-selector-class: com.demo.bbq.repository.menu.menuv1.MenuV1RepositoryImpl

  errors:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.