apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kafka-server
data:
  kafka-transaction-state-log-min-isr: "1"
  kafka-zookeeper-connect: "zookeeper-server:2181"
  kafka-authorizer-class-name: "kafka.security.authorizer.AclAuthorizer"
  kafka-offsets-topic-replication-factor: "1"
  kafka-broker-id: "1"
  kafka-inter-broker-listener-name: "INTERNAL"
  kafka-listener-security-protocol-map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
  kafka-advertised-listeners: "INTERNAL://kafka-server:9093,EXTERNAL://-127.0.0.1:9092,DOCKER://host.docker.internal:29092"
  kafka-transaction-state-log-replication-factor: "1"
  kafka-jmx-hostname: "127.0.0.1"
  kafka-allow-everyone-if-no-acl-found: "true"
  kafka-jmx-port: "9999"
  kafka-log4j-loggers: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
