apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: kafka-server
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 9092
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-advertised-listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-listener-security-protocol-map
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-inter-broker-listener-name
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-zookeeper-connect
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-broker-id
            - name: KAFKA_LOG4J_LOGGERS
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-log4j-loggers
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-offsets-topic-replication-factor
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-transaction-state-log-replication-factor
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-transaction-state-log-min-isr
            - name: KAFKA_JMX_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-jmx-port
            - name: KAFKA_JMX_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-jmx-hostname
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-authorizer-class-name
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              valueFrom:
                configMapKeyRef:
                  name: cm-kafka-server
                  key: kafka-allow-everyone-if-no-acl-found
      
