apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  type: NodePort
  selector:
    app: kafka-server
  
  ipFamilies:
    - IPv4
  ports:
    - name: kafka-server
      port: 9092
      nodePort: 30092
