kind: Service
apiVersion: v1
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  type: NodePort
  selector:
    app: kafka-server
  ports:
    - name: kafka-server
      port: 9092
      nodePort: 30092
