apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server-v1
spec:
  replicas: 1
  serviceName: config-server-v1
  selector:
    matchLabels:
      app: config-server-v1
  template:
    metadata:
      labels:
        app: config-server-v1
    spec:
      containers:
        - name: config-server-v1
          image: miguelarmasabt/config-server-v1:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent #load the image from local
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cm-config-server-v1
                  key: eureka-server
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-config-server-v1
                  key: java-opts
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"