kind: Service
apiVersion: v1
metadata:
  name: config-server-v1
  labels:
    app: config-server-v1
spec:
  type: NodePort
  clusterIP: 10.96.1.4 #cluster IP allow backend requests
  ports:
    - name: config-server-v1
      port: 8888
      nodePort: 30888
  selector:
    app: config-server-v1