apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bbq-postgres
  labels:
    app: bbq-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi