apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: keycloak-server
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: keycloak-server
    spec:
      containers:
        - name: keycloak-server
          image: jboss/keycloak:16.0.0
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8080
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: keycloak-user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: keycloak-password
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: db-vendor
      
