apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: keycloak-server
  template:
    metadata:
      labels:
        app: keycloak-server
    spec:
      containers:
        - name: keycloak-server
          image: jboss/keycloak:16.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: keycloak-user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: keycloak-password
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: cm-keycloak-server
                  key: db-vendor
