kind: Service
apiVersion: v1
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  type: NodePort
  selector:
    app: keycloak-server
  ports:
    - name: keycloak-server
      port: 8080
      nodePort: 30180
