apiVersion: v1
kind: Service
metadata:
  name: keycloak-server
  labels:
    app: keycloak-server
spec:
  type: NodePort
  selector:
    app: keycloak-server
  
  ipFamilies:
    - IPv4
  ports:
    - name: keycloak-server
      port: 8080
      nodePort: 30180
