kind: Service
apiVersion: v1
metadata:
  name: menu-v1
  labels:
    app: menu-v1
spec:
  type: NodePort
  selector:
    app: menu-v1
  ports:
    - name: menu-v1
      port: 8012
      nodePort : 30012