apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment-v1
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: payment-v1
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: payment-v1
    spec:
      containers:
        - name: payment-v1
          image: miguelarmasabt/payment:v1.0.1
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8015
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          livenessProbe: #decide whether to restart the pod
            httpGet:
              path: /actuator/health/liveness
              port: 8015
            initialDelaySeconds: 30 #wait for the service to start and stabilize before the first check
            periodSeconds: 30 #frequency of liveness checks
            timeoutSeconds: 5 #If the service is not available after a timeout period, the failure counter is increase
            failureThreshold: 3 #failure threshold to cancel the pod execution and provide a new replica
          readinessProbe: #decide whether to send traffic to the pod
            httpGet:
              path: /actuator/health/readiness
              port: 8015
            initialDelaySeconds: 30 #wait for the service to start and stabilize before the first check
            periodSeconds: 30 #frequency of readiness checks
          env:
            - name: CONFIG_SERVER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: config-server-domain
            - name: MYSQL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: mysql-domain
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: mysql-password
            - name: KAFKA_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: kafka-domain
            - name: CREATE_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: create-topics
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-payment-v1
                  key: java-opts
      
