kind: Service
apiVersion: v1
metadata:
  name: payment-v1
  labels:
    app: payment-v1
spec:
  type: NodePort
  selector:
    app: payment-v1
  ports:
    - name: payment-v1
      port: 8015
      nodePort: 30015
