apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-discovery-server-v1
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: registry-discovery-server-v1
  template:
    metadata:
      labels:
        app: registry-discovery-server-v1
    spec:
      containers:
        - name: registry-discovery-server-v1
          image: miguelarmasabt/registry-discovery-server:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
