apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-@app_name
  labels:
    app: @app_name
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi