apiVersion: v1
kind: Service
metadata:
  name: @app_name
  labels:
    app: @app_name
spec:
  type: NodePort
  selector:
    app: @app_name
  @cluster_ip
  ipFamilies:
    - IPv4
  ports:
    - name: @app_name
      port: @container_port
      nodePort: @node_port