apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  type: NodePort
  selector:
    app: postgres-db
  clusterIP: 10.96.1.3

  ipFamilies:
    - IPv4
  ports:
    - name: postgres-db
      port: 5432
      nodePort: 30032
