kind: Service
apiVersion: v1
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
spec:
  type: NodePort
  selector:
    app: APP_NAME
  ports:
    - name: APP_NAME
      port: PORT
      nodePort : NODE_PORT