apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: APP_NAME
spec:
  replicas: 1
  serviceName: APP_NAME
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: CONTAINER_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: ENVIRONMENT_VARIABLES


