apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-APP_NAME
  labels:
    type: local #it is a plugin support many disks like amazon EBS azure disk etc.  local = local storage devices mounted on nodes.
    app: APP_NAME
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany #many pods on scheduled on different nodes can read and write
  hostPath:
    path: HOST_MOUNT_PATH #path on cluster's node