apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
spec:
  type: NodePort
  clusterIP: CLUSTER_IP #cluster IP allow backend requests
  selector:
    app: APP_NAME
  ipFamilies:
    - IPv4
  ports:
    - name: APP_NAME
      port: PORT
      nodePort: NODE_PORT