apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-adapter-v1
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: auth-adapter-v1
  template:
    metadata:
      labels:
        app: auth-adapter-v1
    spec:
      containers:
        - name: auth-adapter-v1
          image: miguelarmasabt/auth-adapter:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8011
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
            - name: KEYCLOACK_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-auth-adapter-v1
                  key: keycloack-domain
            - name: KEYCLOACK_KEY_RS256
              valueFrom:
                configMapKeyRef:
                  name: cm-auth-adapter-v1
                  key: keycloack-key-rs256
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-auth-adapter-v1
                  key: java-opts
