apiVersion: v1
kind: Service
metadata:
  name: auth-adapter-v1
  labels:
    app: auth-adapter-v1
spec:
  type: NodePort
  selector:
    app: auth-adapter-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: auth-adapter-v1
      port: 8011
      nodePort: 30011
