apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api-gateway-v1
spec:
  selector:
    matchLabels:
      app: api-gateway-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-v1
    spec:
      containers:
        - name: api-gateway-v1
          image: miguelarmasabt/api-gateway-v1:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent #load the image from local
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: eureka-server
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: java-opts
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"