apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: redis-server
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 6379
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: DUMMY
              valueFrom:
                configMapKeyRef:
                  name: cm-redis-server
                  key: dummy
      
