apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  type: NodePort
  selector:
    app: redis-server
  
  ipFamilies:
    - IPv4
  ports:
    - name: redis-server
      port: 6379
      nodePort: 30379
