kind: Service
apiVersion: v1
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  type: NodePort
  selector:
    app: redis-server
  ports:
    - name: redis-server
      port: 6379
      nodePort: 30379
