apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-table-placement-v1
data:
  mongodb-url: mongodb://bbq-user:qwerty@mongo-db:27017/tablePlacement
  java-opts: -Xms256M -Xmx256M
  eureka-server: http://registry-discovery-server-v1:8761/eureka/
