kind: Service
apiVersion: v1
metadata:
  name: table-placement-v1
  labels:
    app: table-placement-v1
spec:
  type: NodePort
  selector:
    app: table-placement-v1
  ports:
    - name: table-placement-v1
      port: 8013
      nodePort: 30013
