apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v1
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: api-gateway-v1
  template:
    metadata:
      labels:
        app: api-gateway-v1
    spec:
      containers:
        - name: api-gateway-v1
          image: miguelarmasabt/api-gateway:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8010
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
          env: 
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: eureka-server
            - name: AUTH_ADAPTER
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: auth-adapter
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: java-opts
