apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: api-gateway-v1
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: api-gateway-v1
    spec:
      containers:
        - name: api-gateway-v1
          image: miguelarmasabt/api-gateway:v1.0.1
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 8010
          
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: AUTH_ADAPTER_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: auth-adapter-domain
            - name: ORDER_HUB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: order-hub-domain
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-api-gateway-v1
                  key: java-opts
      
