apiVersion: v1
kind: Service
metadata:
  name: api-gateway-v1
  labels:
    app: api-gateway-v1
spec:
  type: NodePort
  selector:
    app: api-gateway-v1
  
  ipFamilies:
    - IPv4
  ports:
    - name: api-gateway-v1
      port: 8010
      nodePort: 30010
