server:
  port: 8010

spring:
  application:
    name: api-gateway-v1
  cloud:
    gateway:
      routes:
        - id: order-hub-v1
          uri: http://${ORDER_HUB_DOMAIN:localhost:8018}
          predicates:
            - Path=/bbq/bff/order-hub/v1/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: AuthenticationFilter

configuration:
  show-custom-messages: false
  rest-clients:
    auth-adapter-v1:
      request:
        endpoint: http://${AUTH_ADAPTER_DOMAIN:localhost:8080}/bbq/infrastructure/v1/auth/
        headers:
          Accept: application/json
      variables:
        expected-roles: partners #separate items with comma
  errors:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

custom-logging:
  project-name: ${spring.application.name}
  enabled: true
  sensitive-headers: ["Authorization"]
  sensitive-body-fields: ["accessToken", "report[*].id"]
  header-obfuscation-strategies:
    "Authorization": STANDARD