server:
  port: 8010

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: api-gateway-v1
  cloud:
    gateway:
      routes:
        - id: order-hub-v1
          uri: lb://order-hub-v1
          predicates:
            - Path=/bbq/experience/order-hub/v1/**
            - Method=GET,POST,PUT,DELETE,PATCH
#          filters:
#            - name: AuthenticationFilter

application:
  http-client:
    auth-adapter:
      base-url: ${AUTH_ADAPTER:http://localhost:8011/bbq/infrastructure/v1/auth/}
  user-roles: '{0:"partners"}' #separate items with comma

## actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' #gateway,info,health,metrics
#  endpoint:
#    health:
#      show-details: always
