server:
  port: 8010

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway-v1
  cloud:
    gateway:
      routes:
        - id: order-hub-v1
          uri: http://${ORDER_HUB_DOMAIN:localhost:8018}
          predicates:
            - Path=/bbq/bff/order-hub/v1/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: AuthenticationFilter

application:
  http-client:
    auth-adapter:
      base-url: http://${AUTH_ADAPTER_DOMAIN:localhost:8011}/bbq/infrastructure/v1/auth/
  user-roles: '{0:"partners"}' #separate items with comma

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans, env, loggers, flyway
  endpoint:
    health:
      show-details: always