apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1 #number of pods replicas
  selector: #define how the Deployment identify the pods that it could manage
    matchLabels:
      app: mongo-db
  template: #pod template specification
    metadata:
      labels: #define the labels for all pods
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports: #open the port to allow send and receive traffic in the container
            - containerPort: 27017
          envFrom: #read envars from secret file
            - secretRef:
                name: secret-mongo-db
          volumeMounts:
            #this is the path in the container on which the mounting will take place.
            - mountPath: /var/lib/mongo-db/data
              name: mongo-db-volume-data
            - mountPath: /docker-entrypoint-initdb.d/initdb.js
              subPath: initdb.js
              name: mongo-db-volume-script
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      
      volumes:
        - name: mongo-db-volume-data
          persistentVolumeClaim:
            claimName: pvc-mongo-db
        - name: mongo-db-volume-script
          configMap:
            name: cm-mongo-db
