apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-db
  labels:
    app: mongo-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
