apiVersion: v1
kind: Secret
metadata:
  name: secret-mongo-db
  labels:
    app: mongo-db
type: Opaque #means we can use arbitrary key pair values
data:
  MONGO_INITDB_DATABASE: dGFibGVQbGFjZW1lbnQ=
  MONGO_INITDB_ROOT_PASSWORD: cXdlcnR5DQ==
  MONGO_INITDB_ROOT_USERNAME: YmJxLXVzZXIN
