apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  type: NodePort
  clusterIP: 10.96.1.4 #cluster IP allow backend requests
  selector:
    app: mongo-db
  ipFamilies:
    - IPv4
  ports:
    - name: mongo-db
      port: 27017
      nodePort: 30717
