apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: table-placement-v1
spec:
  replicas: 1
  serviceName: table-placement-v1
  selector:
    matchLabels:
      app: table-placement-v1
  template:
    metadata:
      labels:
        app: table-placement-v1
    spec:
      containers:
        - name: table-placement-v1
          image: miguelarmasabt/table-placement-v1:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8013
          env:
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: cm-table-placement-v1
                  key: eureka-server
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-table-placement-v1
                  key: postgresql-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-table-placement-v1
                  key: postgresql-password
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-table-placement-v1
                  key: postgresql-url
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cm-table-placement-v1
                  key: java-opts
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "640Mi"
              cpu: "1"
