apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-db
  labels:
    app: mysql-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi