kind: Service
apiVersion: v1
metadata:
  name: svc-mysql-db
  labels:
    app: mysql-db
spec:
  clusterIP: 10.96.1.3 #cluster IP allow backend requests
  ipFamilies:
    - IPv4
  ports:
    - name: mysql-db
      port: 3306
      nodePort : 30306
  type: NodePort #type: LoadBalancer
  selector:
    app: mysql-db