version: '3.1'

services:
  product-v1:
    container_name: product-v1
    image: miguelarmasabt/product:v1.0.1
    restart: always
    environment: 
      - MYSQL_HOST=mysql-db:3306
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - DATABASE=db_products
    depends_on:
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8017:8017"

  menu-v1:
    container_name: menu-v1
    image: miguelarmasabt/menu:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=http://config-server-v1:8888
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/db_menu_options?useUnicode=trueSERVICESuseJDBCCompliantTimezoneShift=trueSERVICESuseLegacyDatetimeCode=falseSERVICESserverTimezone=UTC
      - PRODUCT_BASE_URL=http://product-v1:8017/bbq/business/product/v1/
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8012:8012"

  menu-v2:
    container_name: menu-v2
    image: miguelarmasabt/menu:v2.0.1
    restart: always
    environment: 
      - MYSQL_URL=mysql://mysql-db:3306/db_menu_options
      - PRODUCT_V1_BASE_URL=http://product-v1:8017/bbq/business/product/v1
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=dev
    depends_on:
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8016:8016"

  table-placement-v1:
    container_name: table-placement-v1
    image: miguelarmasabt/table-placement:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=http://config-server-v1:8888
      - MONGODB_URL=mongodb://bbq-user:qwerty@mongo-db:27017/tablePlacement
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - mongo-db
    
    networks:
      - dev_environment
    ports:
      - "8013:8013"

  config-server-v1:
    container_name: config-server-v1
    image: miguelarmasabt/config-server:v1.0.1
    restart: always
    environment: 
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8888:8888"

  api-gateway-v1:
    container_name: api-gateway-v1
    image: miguelarmasabt/api-gateway:v1.0.1
    restart: always
    environment: 
      - AUTH_ADAPTER_URL=http://auth-adapter-v1:8011/bbq/infrastructure/v1/auth/
      - ORDER_HUB_DOMAIN=http://order-hub-v1:8018
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8010:8010"

  auth-adapter-v1:
    container_name: auth-adapter-v1
    image: miguelarmasabt/auth-adapter:v1.0.1
    restart: always
    environment: 
      - KEYCLOACK_SERVER=http://keycloak-server:8080/auth/realms
      - KEYCLOACK_KEY_RS256=mH6KTBOtG3B8_UcrOvA6zPn23SdGeqpp5YOp-MHR0Fo
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8011:8011"

  keycloak-server:
    container_name: keycloak-server
    image: jboss/keycloak:16.0.0
    restart: always
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    
    
    networks:
      - dev_environment
    ports:
      - "8091:8080"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment: 
      - DUMMY=dummy
    
    
    networks:
      - dev_environment
    ports:
      - "6379:6379"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    environment: 
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    
    networks:
      - dev_environment
    ports:
      - "9092:9092"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
    
    
    networks:
      - dev_environment
    ports:
      - "2181:2181"

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=qwerty
      - TZ=UTC
    
    volumes:
      - ./../environment/databases/mysql-db/init:/docker-entrypoint-initdb.d
      - ./../environment/databases/mysql-db/data:/data/db
    networks:
      - dev_environment
    ports:
      - "3306:3306"

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=bbq-user
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - MONGO_INITDB_DATABASE=tablePlacement
    
    volumes:
      - ./../environment/databases/mongo-db/init:/docker-entrypoint-initdb.d
      - ./../environment/databases/mongo-db/data:/data/db
    networks:
      - dev_environment
    ports:
      - "27017:27017"


networks:
  dev_environment:
    driver: bridge
    #activate ipv6
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.232.0/24
          gateway: 172.16.232.1
        -
          subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"
